CREATE TABLE students(
id NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
first_name VARCHAR2(100) NOT NULL,
last_name VARCHAR2(100),
email VARCHAR2(100));


select * from students;

DELETE
FROM
    students
WHERE
    first_name = 'Ajmi' OR first_name = 'Kripa';


DROP TABLE students;

DROP TABLE role;
select * from role;

DELETE
FROM
    role
WHERE
    user_name = 'admin';